spring:
  application:
    name: HealthTracker

  data:
    mongodb:
      uri: ${MONGODB_URI}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    lazy-initialization: true
#  This Reduces the startup time of the application from 202 to 58.4 sec.

server:
  port: ${PORT:8080}
  servlet:
    context-path: /health

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,startup

  endpoint:
    health:
      show-details: always

  metrics:
    enable:
      all: true